language: go

go:
  - 1.8
  - 1.9

sudo: required

env:
- CHANGE_MINIKUBE_NONE_USER=true

before_script:
- go get k8s.io/client-go/...

script:
- go vet .
- go test -coverprofile=coverage.txt -covermode=atomic

after_success:
- bash <(curl -s https://codecov.io/bash)
