language: go

go:
  - 1.8
  - 1.9

before_script:
  - go get k8s.io/client-go/...

script:
  - go vet .
  - go test -coverprofile=coverage.txt -covermode=atomic

after_success:
  - bash <(curl -s https://codecov.io/bash)
